/*=====================================================================================
-- BUSINESS QUESTION: How concentrated are revenue and profit across customers?

-- PURPOSE:
--   Measure what percentage of total revenue and profit is generated by the
--   top 10% and top 20% of customers, to assess dependency on high-value customers.

-- DATA & SCOPE:
--   - Customer summary table (aggregated at customer level)
--   - Includes customers with recorded revenue and profit

-- APPROACH:
--   1. Rank customers separately by total revenue and total profit
--   2. Identify top 10% and top 20% customer thresholds
--   3. Use conditional aggregation to calculate contribution of each group
--      without filtering out the full dataset

-- ASSUMPTIONS & NOTES:
--   - Segments are cumulative (Top 20% includes Top 10%)
--   - Revenue and profit concentration are evaluated independently

-- OUTPUT:
--   Percentage contribution of Top 10% and Top 20% customers for both
--   revenue and profit
=====================================================================================*/

WITH customer_rank AS (
	SELECT
		customer_key,
		total_revenue,
		total_profit,
		ROW_NUMBER() OVER(ORDER BY total_revenue DESC) rn_revenue,
		ROW_NUMBER() OVER(ORDER BY total_profit DESC)  rn_profit
	FROM gold.customer_summary 
),
threshold AS (
	SELECT
		CEIL(COUNT(*) * 0.10) AS ten_pct,
		CEIL(COUNT(*) * 0.20) AS twenty_pct
	FROM gold.customer_summary 
),
totals AS (
	SELECT
		SUM(total_revenue) AS revenue,
		SUM(total_profit)  AS profit 
	FROM gold.customer_summary
)
SELECT 
	'Top 10%' AS segment,
	ten_pct   AS customer_count,
	ROUND(SUM(CASE 
				WHEN rn_revenue  <= ten_pct THEN total_revenue END) / 
				revenue * 100, 2) AS revenue_contribution_pct,
	ROUND(SUM(CASE 
				WHEN rn_profit <= ten_pct THEN total_profit END) / 
				profit * 100, 2) AS profit_contribution_pct
FROM customer_rank 
CROSS JOIN totals 
CROSS JOIN threshold 
GROUP BY 
	customer_count,
	revenue,
	profit
	
UNION ALL

SELECT 
	'Top 20%' AS segment,
	twenty_pct AS customer_count,
	ROUND(SUM(CASE 
				WHEN rn_revenue  <= twenty_pct THEN total_revenue
			   END) / revenue * 100, 2) AS revenue_contribution_pct,
	ROUND(SUM(CASE 
				WHEN rn_profit <= twenty_pct THEN total_profit
			  END) / profit * 100, 2) AS profit_contribution_pct
FROM customer_rank 
CROSS JOIN totals 
CROSS JOIN threshold 
GROUP BY 
	customer_count,
	revenue,
	profit
;

--==============================
/*	Output:
--==============================

segment|customer_count|revenue_contribution_pct|profit_contribution_pct
-------+--------------+------------------------+-----------------------
Top 10%|          8787|                   25.72|                  26.33
Top 20%|         17574|                   43.50|                  44.26
*/